// Vendors the Cubism SDK for Web into cubism/: the Framework sources, the Core,
// its types, and the WebGL shaders inlined as strings.
//
//   npm run sync-cubism            # the version pinned below
//   npm run sync-cubism -- 5-r.6   # another release
//
// Everything under cubism/ is generated. Change this script, never those files.

import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { unzipSync } from "fflate";

const VERSION = process.argv[2] ?? "5-r.5";
const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "cubism");
const URL = `https://cubism.live2d.com/sdk-web/bin/CubismSdkForWeb-${VERSION}.zip`;

const HEADER = `// Generated by scripts/sync-cubism.mjs from Cubism SDK for Web ${VERSION}. Do not edit.\n`;

// Each patch must match exactly once, so an SDK update that moves the code fails loudly.
const PATCHES = {
  // The shaders are fetched from a directory on the server; read them from the bundle instead.
  "rendering/cubismshader_webgl.ts": [
    [
      "  private async loadShader(url: string): Promise<string> {\n    const response = await fetch(url);\n    return await response.text();\n  }",
      "  private async loadShader(url: string): Promise<string> {\n    return shaders[url.slice(url.lastIndexOf('/') + 1)] ?? '';\n  }",
    ],
    [
      "export class CubismShader_WebGL {",
      "import { shaders } from '../shaders';\n\nexport class CubismShader_WebGL {",
    ],
    // One shader set per context lives until the framework is disposed; let a destroyed canvas drop its own.
    [
      "  public getShader(gl: WebGLRenderingContext): CubismShader_WebGL {",
      "  public removeGlContext(gl: WebGLRenderingContext): void {\n    this._shaderMap.get(gl)?.release();\n    this._shaderMap.delete(gl);\n  }\n\n  public getShader(gl: WebGLRenderingContext): CubismShader_WebGL {",
    ],
  ],
};

function patch(path, source) {
  for (const [from, to] of PATCHES[path] ?? []) {
    const count = source.split(from).length - 1;
    if (count !== 1) throw new Error(`Patch for ${path} matched ${count} times:\n${from}`);
    source = source.replace(from, to);
  }
  return source;
}

function strip(prefix, files) {
  return Object.fromEntries(
    Object.entries(files)
      .filter(([name, data]) => name.startsWith(prefix) && data.length > 0)
      .map(([name, data]) => [name.slice(prefix.length), data]),
  );
}

console.log(`Downloading ${URL}`);
const response = await fetch(URL);
if (!response.ok) throw new Error(`${response.status} ${URL}`);
const zip = unzipSync(new Uint8Array(await response.arrayBuffer()));
const base = Object.keys(zip).find((name) => name.endsWith("/Framework/src/live2dcubismframework.ts"))?.split("Framework/")[0];
if (base === undefined) throw new Error("No Framework/src in the SDK archive");

const text = (data) => new TextDecoder().decode(data);
const framework = strip(`${base}Framework/src/`, zip);
const shaderFiles = strip(`${base}Framework/Shaders/WebGL/`, zip);
const core = strip(`${base}Core/`, zip);

await rm(OUT, { recursive: true, force: true });

async function emit(path, content) {
  await mkdir(dirname(join(OUT, path)), { recursive: true });
  await writeFile(join(OUT, path), content);
}

// The Framework is written for loose compiler settings; the library's own code is strict.
for (const [path, data] of Object.entries(framework)) {
  if (!path.endsWith(".ts")) continue;
  await emit(path, `// @ts-nocheck\n${HEADER}${patch(path, text(data))}`);
}
for (const path of Object.keys(PATCHES)) {
  if (!(path in framework)) throw new Error(`Patched file ${path} is missing from the SDK`);
}

const shaders = Object.entries(shaderFiles)
  .filter(([name]) => /\.(frag|vert)$/.test(name))
  .map(([name, data]) => `  ${JSON.stringify(name)}: ${JSON.stringify(text(data))},`);
await emit("shaders.ts", `${HEADER}export const shaders: Record<string, string> = {\n${shaders.join("\n")}\n};\n`);

// The Core is a classic script that declares a global. Wrapping it as a module lets
// bundlers split it into its own chunk without eval, blob URLs, or a CDN. The
// parameters shadow its UMD tail and its Node-only require("fs"), which bundlers
// would otherwise rewrite into their own AMD/CommonJS handling or fail to resolve.
// The loader assigns the global, so the export is used and no minifier can drop
// the chunk as side-effect free.
const coreSource = text(core["live2dcubismcore.min.js"]);
await emit(
  "core.js",
  `${HEADER}export default (function (exports, module, define, require) {\n${coreSource}\nreturn Live2DCubismCore;\n})();\n`,
);
await emit("core.d.ts", `${HEADER}declare const core: typeof Live2DCubismCore;\nexport default core;\n`);
await emit("live2dcubismcore.d.ts", text(core["live2dcubismcore.d.ts"]));

for (const [name, data] of [
  ["LICENSE.md", zip[`${base}LICENSE.md`]],
  ["CORE_LICENSE.md", core["LICENSE.md"]],
  ["RedistributableFiles.txt", core["RedistributableFiles.txt"]],
]) {
  if (data) await emit(name, data);
}
await emit("VERSION", `${VERSION}\n`);
// The Framework imports types without `import type`. Per-file transpilers (esbuild
// in Vite dev) read the nearest tsconfig, and with verbatimModuleSyntax they would
// keep those imports and fail at runtime.
await emit(
  "tsconfig.json",
  `${JSON.stringify({ extends: "../tsconfig.json", compilerOptions: { verbatimModuleSyntax: false, isolatedModules: false } }, null, 2)}\n`,
);

async function count(dir) {
  let total = 0;
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    total += entry.isDirectory() ? await count(join(dir, entry.name)) : 1;
  }
  return total;
}
console.log(`Wrote ${await count(OUT)} files to ${relative(ROOT, OUT)}/ (${shaders.length} shaders)`);
